import * as Verification from '../verification';

export const PropTypes = {
    typeof: Verification.assertTypeof,
    string: Verification.assertString,
    boolean: Verification.assertBoolean,
    number: Verification.assertNumber,
    pstNumber: Verification.assertPstNumber,
    integer: Verification.assertInt,
    pstInteger: Verification.assertPstInt,
    noEmptyOrNull: Verification.assertNoEmptyOrNull,
    function: Verification.assertFunction,
    object: Verification.assertObject,
    array: Verification.assertArray,
    noNullOrUndefined: Verification.assertNoNullOrUndefined,
    jsonObject: Verification.assertJSONObject,
    color: Verification.checkColor,
    instanceOf: Verification.assertInstanceOf,
    regexp: Verification.assertRegExp,
    match: Verification.assertMatch,
    oneOf: Verification.assertOneOf,
    oneOfType: Verification.assertOneOfType,
    arrayOf: Verification.assertArrayOf,
    contains: Verification.assertContains,
    minLength: Verification.assertMinLength,
    maxLength: Verification.assertMaxLength,
    length: Verification.assertLength,
    min: Verification.assertMin,
    max: Verification.assertMax,
    range: Verification.assertRange,
    shape: Verification.assertShape,
    allOf: Verification.assertAllOf,
    nd: Verification.assertAllOf,
    or: Verification.assertOneOfType,
    required: Verification.assertNoNullOrUndefined,
    false: Verification.assertFalse
}